; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[commmon]
platform = espressif32
board = esp32dev
framework = arduino

[env:engine]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
build_flags = -DNODE_ENGINE

[env:sensor]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
build_flags = -DNODE_SENSOR

[env:actuator]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
build_flags = -DNODE_ACTUATOR

[env:dashboard]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
build_flags = -DNODE_DASHBOARD